name: Daily Stock Update

# Triggers: run on push to main OR manually
on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger from Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # 4️⃣ Run the update script
      - name: Run update_data.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/update_data.py

